# Generated by Django 3.2.7 on 2021-09-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YamiFood', '0002_delivery_order_order_details_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.CharField(default='', max_length=50),
        ),
    ]
